### ISSUE TITLE
Manula trigger, initiating user parameter $USER

### ISSUE THREAD

**Issue by amirhadar** [ParameterizedBuilds/parameterized-builds#49] opened 2016-11-24 09:26 UTC
Hi,
When manual trigger is done on a feature branch or BugFix, the user would like to receive email with the results of the unit-test from Jenkins.
Currently there is no way to pass a parameter to the Jenkins with the initiating user.

I think that if this add-on will provide additional parameter for the trigger: $USER 
It will provide the jenkins with the needed information to send the results to the intiator

BR
Amir Hadar

**Comment by edwardtew** [comment] 2016-11-24 19:02
This is not necessary because the BitBucket user has to link their bb account to the jenkins account in their bb profile page.

Jenkins uses a unique token for each user and this plugin use this to identify the user. Passing a parameter in the request is an open invitation to abuse and spam emails being sent to other users.

**Comment by amirhadar** [comment] 2016-11-29 19:59
Our jenkins login username is employee id (Active Directory sync)
Our BitBucket login username is employee email (also from Active Directory sync)
Why? I don't know but it cannot be changed (too many infra and active projects)

When using user-token there is no match because of the different username used in the different systems.

I suggest to add "Jenkins username" to the Jenkins Settings. This way the username dont have to be with the same. (Leave blank for same username)

**Comment by edwardtew** [comment] 2016-11-29 21:34
As part of the plugin it installed a mechanism to link your BB account to your Jenkins Account via the Jenkins token.

**Comment by KyleLNicholls** [comment] 2016-12-01 01:45
I think the issue is your bitbucket is sending username@email:uniquetoken and jenkins is expecting username:uniquetoken for authentication. Not sure how (or if I want) to fix this.

**Comment by amirhadar** [comment] 2016-12-08 08:06
The problem is that BitBucket authenticate using Email while the Jenkins authenticate using Employee ID (19650). Both uses the Active Directory for authentication but different fields.

When BitBucket authenticate to Jenkins it using the user:
amir.hadar_sandisk.com

Which is a user that does not exists in Jenkins although it is the same user. When trying to put the token of the real jenkins user I get:
Invalid password/token for user: amir.hadar_sandisk.com


What I am asking is one of the following:
 - To be able to provide in the Settings the Jenkins username to use in the authentication (default blank)
Or
- Provide $USERID as part of the Manual trigger so Jenkins job could access the user info using REST API and will know who triggered the Manual build.

**Comment by a-hacker** [comment] 2022-01-03 23:17
Closing this as enhancements are no longer being worked on.

**Closed by a-hacker** 2022-01-03 23:17 UTC
Labels: enhancement
