### ISSUE TITLE
Issue when using "/" in the "Server Nickname" field

### ISSUE THREAD

**Issue by marceloavilaoliveira** [ParameterizedBuilds/parameterized-builds#241] opened 2019-11-18 19:19 UTC
![S2019_11_18-02](https://user-images.githubusercontent.com/20242819/69082666-508e7a00-0a1f-11ea-9490-7b8157fb23d6.png)
- Parameterized Builds for Jenkins plugin version 4.0.9
- Bitbucket version 6.3.2
- Jenkins Version 2.176.3

In the Bitbucket > Project settings > Jenkins Settings page, if the Jenkins settings are saved but the "Server Nickname" field contains the "/" character, it's impossible to change or clear the settings after that.

If you click on the "Save" button the message "Saving settings..." is showed forever and if you click on "Clear Jenkins Settings" the message "Could not remove jenkins server" is showed.

The plugin seems to work correctly but it's impossible to change or clear the settings.

**Comment by a-hacker** [comment] 2019-11-18 20:52
Hi @marceloavilaoliveira. I was able to reproduce this bug locally. It looks like it is just a simple uri encoding issue. Unfortunately, when I added proper encoding, Bitbucket seemed to block the request for some reason. I'll need to investigate this a bit more to find a suitable solution. For now, I'd recommend just avoiding forward slashes in the alias until this is resolved.

If your settings are already stuck, run `curl -X DELETE <bitbucket base url>/rest/parameterized-builds/latest/projects/<project id>/servers/<some string without a forward slash>`. That should clear out the bad settings.

**Comment by marceloavilaoliveira** [comment] 2019-11-26 13:12
Hi @a-hacker. I tried to execute the "curl -X DELETE" command but it didn't work. What should I use in the <some string without a forward slash> string? I mean, the server I want to delete HAS a forward slash in the name. I tried to use "/" and "%2F" but I got "Invalid URI: noSlash" answer. If I remove the "/" from the server name it doesn't do anything (I think it's not finding the server to be deleted).

**Comment by a-hacker** [comment] 2019-11-26 13:46
Hey @marceloavilaoliveira. That's odd that the curl didn't work. The REST endpoint is designed for handling multiple servers per project but that functionality doesn't exist yet so the server nickname used at the end of the url goes unused. That's why I suggested you use any string without "/" in it.

Was the issue that the curl command completed successfully but did not remove the server definition or that the curl command returned a 4XX or 5XX status code? The endpoint does require authentication which I forgot to mention in my previous response.

**Comment by marceloavilaoliveira** [comment] 2019-11-26 14:27
Success! I used the "project key" instead of the "project id" (with a aleatory server name string) and it worked. Thanks a lot!!!

**Comment by a-hacker** [comment] 2020-01-17 15:11
Fixed in 4.0.10

**Closed by a-hacker** 2020-01-17 15:11 UTC
Labels: bug

**Comment by marceloavilaoliveira** [comment] 2020-01-20 12:51
I updated to 4.0.10 and it's OK now. Thanks.
